version: '3'

services:
   registry:
     image: registry:2
     container_name: registry
     restart: always
     ports:
       - 5000:5000
     environment:
       REGISTRY_HTTP_ADDR: 0.0.0.0:5000
     volumes:
       - /opt/registry:/var/lib/registry
  
   nginx:
     image: nginx:alpine
     container_name: nginx
     restart: always
     ports:
       - 443:443
     links:
       - registry:registry
     volumes:
       - ./certs/domain.crt:/etc/nginx/conf.d/domain.crt:ro
       - ./certs/domain.key:/etc/nginx/conf.d/domain.key:ro
       - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro
       - ./auth/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd:ro

